Layout/EndOfLine:
   Enabled: False
Metrics/BlockLength:
   Enabled: False
Style/Documentation:
   Enabled: False
Metrics/MethodLength:
   Enabled: False
Layout/LineLength:
   Enabled: False
Metrics/ClassLength:
   Enabled: False
Metrics/PerceivedComplexity:
   Enabled: False
Metrics/CyclomaticComplexity:
   Enabled: False
Metrics/AbcSize:
   Enabled: False
Naming/AccessorMethodName:
   Enabled: False
Style/GuardClause:
   Enabled: False