 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/holds", type: :request do
  
  # Hold. As you add validations to Hold, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hold.create! valid_attributes
      get holds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hold = Hold.create! valid_attributes
      get hold_url(hold)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hold_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hold = Hold.create! valid_attributes
      get edit_hold_url(hold)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hold" do
        expect {
          post holds_url, params: { hold: valid_attributes }
        }.to change(Hold, :count).by(1)
      end

      it "redirects to the created hold" do
        post holds_url, params: { hold: valid_attributes }
        expect(response).to redirect_to(hold_url(Hold.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hold" do
        expect {
          post holds_url, params: { hold: invalid_attributes }
        }.to change(Hold, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post holds_url, params: { hold: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hold" do
        hold = Hold.create! valid_attributes
        patch hold_url(hold), params: { hold: new_attributes }
        hold.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hold" do
        hold = Hold.create! valid_attributes
        patch hold_url(hold), params: { hold: new_attributes }
        hold.reload
        expect(response).to redirect_to(hold_url(hold))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hold = Hold.create! valid_attributes
        patch hold_url(hold), params: { hold: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hold" do
      hold = Hold.create! valid_attributes
      expect {
        delete hold_url(hold)
      }.to change(Hold, :count).by(-1)
    end

    it "redirects to the holds list" do
      hold = Hold.create! valid_attributes
      delete hold_url(hold)
      expect(response).to redirect_to(holds_url)
    end
  end
end
